services:
  - type: web
    name: sovereign-credit-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn blackbird_api_dashboard:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: PORT
        value: 10000
